version: '3'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
      - redis
  database:
    build:
      context: .
      dockerfile: Dockerfile.DB
    ports:
      - 3307:3307
  redis:
    build: 
      context: ./redis
      dockerfile: Dockerfile.redis
    ports:
      - 6379:6379