FROM redis

RUN mkdir -p /redis

WORKDIR /redis

# 로컬의 Redis 폴더에 있는 redis.conf 파일을 컨테이너 내부로 복사
COPY ./redis/redis.conf /redis/redis.conf

# Redis를 설정 파일과 함께 실행
CMD ["redis-server", "/redis/redis.conf"]