name: deploy
on:
  pull_request:
    branches: ['main']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: excute remote ssh & deploy server
        uses: NeedU/ssh-action@main
        with:
          host: ${{ secrets.NEEDU_SSH_HOST }}
          username: ${{ secrets.NEEDU_SSH_USERNAME }}
          password: ${{ secrets.NEEDU_SSH_PASSWORD }}
          port: ${{ secrets.NEEDU_SSH_PORT }}
          script: |
            cd /root/Needu
            git pull
